[package]
name = "nickwb_advent_2020"
version = "0.1.0"
authors = ["Nick Young <nick@nickwb.net>"]
edition = "2018"
default-run = "runall"

[features]
default = []
slow_problems = []

[dependencies]
regex = "1.3.1"
lazy_static = "1.4.0"
rayon = "1.5.0"
num = "0.3.1"
itertools = "0.9.0"